# site name
prefixName: lovelves
siteName: 的博客
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://cdn.jsdelivr.net/gh/lingdas/note/img/avactor.jpeg
url: www.lovelves.cn
description: Live your life with passion! With some drive!
cdn: 
pjax: 1
# 1开启
mathjax: 1

notice: 
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
    笔记: {path: /booklist/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }
  } }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}
  } }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }
 


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://pic4.zhimg.com/v2-7e3bd74fc2385af3251553adceec67a8_r.jpg?source=1940ef5c
  - https://pic4.zhimg.com/v2-23fe50c0f5c916a8a319e5afdec5b044_r.jpg?source=1940ef5c
  - https://pic4.zhimg.com/v2-ee4e5d2641987212a1b874fc492fc55c_r.jpg?source=1940ef5c
  - https://cdn.jsdelivr.net/gh/lingdas/note/img/16.jpg
  - https://cdn.jsdelivr.net/gh/lingdas/note/img/13.jpg
  - https://cdn.jsdelivr.net/gh/lingdas/note/img/10.jpg
  - https://cdn.jsdelivr.net/gh/lingdas/note/img/20.jpg


# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: /2021/06/15/酷我音乐爬取/, title: 酷我音乐爬取, desc: 爬虫练习, img: https://cdn.jsdelivr.net/gh/lingdas/note/img/10.jpg}
  - {url: /2021/06/14/hexo/, title: hexo安装使用, desc: hexo安装使用技巧, img: https://cdn.jsdelivr.net/gh/lingdas/note/img/1.jpg}
  - {url: /music/, title: 歌单, desc: 歌单, img: https://cdn.jsdelivr.net/gh/lingdas/note/img/14.jpg}



# your site build time or founded date
siteBuildingTime: 06/17/2021

#social  url, img PC端配置
# social:
#   github: {url: http://github.com/honjun, img: /img/social/github.png}
#   sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
#   wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
#   zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
#   email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
#   wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
#   wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
# msocial:
#   github: {url: http://github.com/honjun, fa: fa-github, color: 333}
#   weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
#   qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  alipay: /images/donate/1623934946669.jpg
  wechat: /images/donate/WechatIMG10.png
  wechatSQ: /images/donate/WechatIMG11.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

# aplayer: 
#   id: 2660651585
#   server: netease
#   type: playlist
#   fixed: true
#   autoplay: false
#   loop: all
#   order: random
#   preload: auto
#   volume: 0.7
#   mutex: true

# Valine
valine: true
v_appId: eBIOWlNSti1cF7QQKTdnAMF5-gzGzoHsz
v_appKey: vWB0QiSYnTUHzNWujmBXrXBF

